// Punoshristi "Eco-Cycle" design system tokens — kept 1:1 with the approved
// UI/UX mockups (see punosristi_eco_recycle_app_ui_ux/original_ui_designs).
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#bbc5be',
        'on-secondary-fixed': '#002204',
        'primary-fixed': '#aef3b1',
        'surface-bright': '#fcf9f8',
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#1a5c2a',
        'inverse-primary': '#93d697',
        'surface-container-highest': '#e5e2e1',
        'on-secondary-fixed-variant': '#005313',
        'secondary-container': '#91f78e',
        'tertiary-fixed': '#dbe5dd',
        'on-tertiary-fixed': '#151d19',
        'secondary-fixed-dim': '#78dc77',
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#bfc9c2',
        'primary-fixed-dim': '#93d697',
        'on-background': '#1c1b1b',
        'on-primary-fixed-variant': '#0c5221',
        'on-primary-fixed': '#002108',
        'outline-variant': '#c0c9bc',
        error: '#ba1a1a',
        'surface-tint': '#2a6b37',
        'surface-container': '#f0eded',
        'on-primary-container': '#8fd394',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#404943',
        background: '#fcf9f8',
        tertiary: '#323b36',
        primary: '#004317',
        'inverse-on-surface': '#f3f0ef',
        'surface-dim': '#dcd9d9',
        secondary: '#006e1c',
        'on-secondary-container': '#00731e',
        outline: '#717a6f',
        'surface-variant': '#e5e2e1',
        'on-surface-variant': '#40493f',
        'on-surface': '#1c1b1b',
        surface: '#fcf9f8',
        'tertiary-container': '#49524c',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#94f990',
        'on-primary': '#ffffff',
        'surface-container-high': '#eae7e7',
        'surface-container-low': '#f6f3f2',
        'inverse-surface': '#313030',
        'error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        lg: '24px',
        base: '8px',
        md: '16px',
        xs: '4px',
        xl: '32px',
        sm: '12px',
        'margin-mobile': '20px',
        gutter: '16px',
        'margin-desktop': '40px',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-xl': ['"Plus Jakarta Sans"'],
        'body-md': ['"Plus Jakarta Sans"'],
        'label-md': ['"Plus Jakarta Sans"'],
        'body-lg': ['"Plus Jakarta Sans"'],
        'headline-lg': ['"Plus Jakarta Sans"'],
        'headline-lg-mobile': ['"Plus Jakarta Sans"'],
        'title-md': ['"Plus Jakarta Sans"'],
      },
      fontSize: {
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg-mobile': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'title-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
